#!/usr/bin/env bash
# prints Best School 10 times using the while loop.
#   on the 9th iteration print Hi before Best School.

a=0

while [ $a -lt 10 ]
do
  if [ $a -eq 9 ]
  then
    echo "Hi"	
  fi
  echo "Best School"
  (( a++ ))
done
